# ใช้ image สำหรับ build React
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Image จริงสำหรับ serve static
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# ใช้ nginx default conf
EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]
