version: "3.9"

services:
  backend:
    build:
      context: ./backend        # ✅ ชี้ไปที่โฟลเดอร์ backend
      dockerfile: Dockerfile    # ใช้ชื่อ Dockerfile (หรือระบุชื่อถ้าเปลี่ยน)
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app          # mount code ในกรณีพัฒนา (ถ้าไม่ต้องการ hot-reload ตัดออก)
    restart: always

  frontend:
    build:
      context: ./frontend       # ✅ ชี้ไปที่โฟลเดอร์ frontend
      dockerfile: Dockerfile
    container_name: node_frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app         # mount code ในกรณีพัฒนา (ถ้าไม่ต้องการ hot-reload ตัดออก)
    restart: always
